[package]
name = "gpg-keytag"
version = "0.1.0"
authors = ["Grégoire Détrez <gregoire@fripost.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
